apisix:
  node_listen: 9080
  enable_admin: true
  enable_admin_cors: true
  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin
  enable_debug: false
  enable_dev_mode: false
  enable_reuseport: true
  enable_ipv6: false
  config_center: etcd
  enable_server_tokens: false

etcd:
  host:
    - "http://etcd:2379"
  prefix: "/apisix"
  timeout: 30
  api_version: v3

nginx_config:
  error_log: "/dev/stderr"
  error_log_level: "warn"
  worker_processes: "auto"
  worker_rlimit_nofile: 20480
  event:
    worker_connections: 10620
    use: epoll
    multi_accept: "on"
  http:
    access_log: "/dev/stdout"
    keepalive_timeout: 60s
    client_header_timeout: 60s
    client_body_timeout: 60s
    send_timeout: 10s
    underscores_in_headers: "on"
    real_ip_header: "X-Real-IP"
    real_ip_recursive: "on"
    real_ip_from:
      - 127.0.0.0/24
      - 192.168.0.0/16
      - 172.16.0.0/12
      - 10.0.0.0/8